// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCalYc7U3E4HuU41h5t6ONqKM-vQjAzRmU',
    appId: '1:929190672324:web:50ef9d22c8a9b6e75cd691',
    messagingSenderId: '929190672324',
    projectId: 'udemy-chat-app-5c7a9',
    authDomain: 'udemy-chat-app-5c7a9.firebaseapp.com',
    storageBucket: 'udemy-chat-app-5c7a9.appspot.com',
    measurementId: 'G-G3D6ZDBK7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwC-yHqiGvWQu3ODCcweDKjxLkGXWRDCc',
    appId: '1:929190672324:android:2066e589b0f358e45cd691',
    messagingSenderId: '929190672324',
    projectId: 'udemy-chat-app-5c7a9',
    storageBucket: 'udemy-chat-app-5c7a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuULJoai4nBVz0tlOq1poVBoz9Cy0tBaA',
    appId: '1:929190672324:ios:12cb53a6306e014f5cd691',
    messagingSenderId: '929190672324',
    projectId: 'udemy-chat-app-5c7a9',
    storageBucket: 'udemy-chat-app-5c7a9.appspot.com',
    iosBundleId: 'com.example.udemyChatApp',
  );
}
